# 程序基本信息
name: "go-gateway" # 程序名称
version: "v0.1" # 版本号
#mode: "dev" # 程序运行的模式，这里是开发模式
mode: "release" # 程序运行的模式，这里是线上
start_time: "2020-12-15"
time_location: "Asia/Shanghai"
machine_id: 1
port: 8080 # 程序运行的端口

http:
  read_time: 10
  write_time: 10
  max_header_bytes: 20
  allow_ip: [
    "127.0.0.1",
    "::1" # localhost 会被解析成::1
  ]

# log
log:
  level: "debug" # x
  filename: "./logs/go-gateway.log"
  max_size: 200 # 日志最大容量（单位 MB）
  max_age: 30 # 备份存储最大时间
  max_backup: 7 # 日志最大备份数量

# auth
session:
  redis_server: "127.0.0.1:6379"   #redis session server
  redis_password: "644315"

auth:
  jwt_expire: 168 # 过期时间为一周（24 * 7）

cluster:
  cluster_ip: "127.0.0.1"
  cluster_port: "8880"
  cluster_ssl_port: "4433"

swagger:
  title: "Go-Gateway swagger API"
  desc: "This is a sample server caller server."
  host: "127.0.0.1:8080"
  base_path: ""